### ISSUE TITLE
Localization from SPM not works

### ISSUE THREAD

**Issue by khorbushko** [piterwilson/WorldGreetings-app-sample#1]
HI

I'm currently trying to implement localization using SP, and found this sample, but it's not work.
Looks like u have additional Localizable.strings files in project itself, that's why it's work. But if u remove them from project and use only localized SP - this project want work.

Can u please check this point?

**Comment by khorbushko** [comment]
I described similar issue here https://stackoverflow.com/q/66694610/2012219 - if u know where is the poblem - can u please advice?

**Comment by piterwilson** [comment]
Hello @khorbushko This repo doesn't use SPM at all so I think you got a bit confused here. I do have a sample app using SPM localization here https://github.com/piterwilson/WorldGreetings-final and you can read this blog post about the whole topic here http://piterwilson.com/blog/localization-with-swift-package-manager

**Comment by khorbushko** [comment]
ah sorry, yes, i believe i make an error opening issue on won g repo, sorry, but problem actually exist. I already found the solutions (if needed, u can check the link to SO post) thanks
